version: '3'
services:
  redis:
    image: redis
    ports:
    - "6379:6379"
  zookeeper:
    image: zookeeper:3.4.14
    ports:
    - "2181:2181"
    - "2888:2888"
    - "3888:3888"
#  dubbo-simple-registry:
#    image: dubbo/simple-registry
#    ports:
#      - "20888:20888"
#      - "9090:9090"
  