###@see org.mvnsearch.PortalController.index
### invoke service from client
GET http://localhost:2080/

### invoke reactive
GET http://localhost:2080/reactive/user

###@see org.mvnsearch.spring.boot.dubbo.DubboEndpoint.invoke
### get dubbo service metrics
GET http://localhost:20882/actuator/dubbo

### prometheus metrics format
GET http://localhost:20882/actuator/prometheus

###